# Inspect the off-shell HZZ ntuple

**Input:** `My Drive/Colab Notebooks/HZZ_OffShell/dataset_wDR_mean_origIndex.h5`

In Colab, choose **Runtime → Run all**, then authorize the Drive mount. A CPU runtime is sufficient. The notebook opens the original HDF5 file read-only and reads small samples without copying the full file into RAM.

It reports groups, dataset shapes, data types, stored attributes, available column labels, example entries, and sampled numerical/categorical diagnostics. Negative weights are retained and counted. Dataset shapes are exact; sampled counts and distributions are not full-file totals.

The last cell writes `.inspection.txt` and `.inspection.json` reports beside the input file in Drive. After running, tell me the reports are ready; I can read them directly. The reports contain a few example entries, so keep them in Drive rather than committing them to the public repository.

## 1. Mount Drive and set the input

The default path matches the project folder. To inspect a different file or run locally, change `FILE_PATH`. `SAMPLE_ROWS` is a maximum per dataset, split across up to five small windows; it is not a random sample.

In [1]:
from pathlib import Path
from datetime import datetime, timezone
from collections import Counter
import json
import math
import pickletools

import h5py
import numpy as np
import pandas as pd
from IPython.display import display

try:
    from google.colab import drive
except ImportError:
    print("Local runtime: set FILE_PATH to your local HDF5 file below.")
else:
    drive.mount("/content/drive")

print(f"h5py {h5py.__version__} | NumPy {np.__version__} | pandas {pd.__version__}")

Mounted at /content/drive
h5py 3.14.0 | NumPy 2.1.3 | pandas 2.2.3

In [2]:
FILE_PATH = Path("/content/drive/MyDrive/Colab Notebooks/HZZ_OffShell/dataset_wDR_mean_origIndex.h5")

SAMPLE_ROWS = 2000
PREVIEW_ROWS = 3
MAX_SAMPLE_BYTES = 8 * 1024**2  # Fixed-size requested data per dataset; compression can require extra I/O.
MAX_DIAGNOSTIC_COLUMNS = 512

assert SAMPLE_ROWS > 0 and PREVIEW_ROWS > 0 and MAX_SAMPLE_BYTES > 0
if not FILE_PATH.is_file():
    raise FileNotFoundError(f"File not found: {FILE_PATH}\nCheck the Drive mount and FILE_PATH.")
print(f"Input: {FILE_PATH}")
print(f"File size: {FILE_PATH.stat().st_size:,} bytes ({FILE_PATH.stat().st_size / 1024**3:.3f} GiB)")

Input: /content/drive/MyDrive/Colab Notebooks/HZZ_OffShell/dataset_wDR_mean_origIndex.h5
File size: 3,626,490,080 bytes (3.377 GiB)

## 2. Inspection helpers

These helpers use `h5py` for structural inspection. They recognize compound fields and common column-label conventions, including pandas fixed-format blocks. Variable-length non-text object payloads are left unread; metadata is never unpickled. Any sampling error is recorded with its dataset path.

In [3]:
def json_value(value, limit=10000):
    """Make HDF5/NumPy values readable without deserializing pickled objects."""
    if isinstance(value, np.void) and value.dtype.names:
        return {name: json_value(value[name], limit) for name in value.dtype.names}
    if isinstance(value, np.ndarray):
        if value.size > limit:
            return {"shape": list(value.shape), "first_values": json_value(value.ravel()[:limit]),
                    "truncated": True}
        return json_value(value.tolist(), limit)
    if isinstance(value, np.generic):
        return json_value(value.item(), limit)
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="backslashreplace")
    if isinstance(value, (list, tuple)):
        return [json_value(x, limit) for x in value]
    if isinstance(value, dict):
        return {str(k): json_value(v, limit) for k, v in value.items()}
    if isinstance(value, float) and not np.isfinite(value):
        return str(value)
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    return repr(value)


def read_attributes(obj):
    result = {}
    for name in obj.attrs:
        try:
            aid = obj.attrs.get_id(name)
            if aid.shape is None:
                result[name] = {"null_attribute": True, "dtype": str(aid.dtype)}
            elif math.prod(aid.shape) * aid.dtype.itemsize > MAX_SAMPLE_BYTES:
                result[name] = {"skipped_large_attribute": True, "shape": list(aid.shape)}
            else:
                result[name] = json_value(obj.attrs[name])
        except Exception as exc:
            result[name] = {"read_error": str(exc)}
    return result


def read_sample(ds):
    """Read up to five small, nonoverlapping windows spread across the row axis."""
    if ds.shape is None or ds.size == 0:
        return None, [], "Null or empty dataset."
    is_text = h5py.check_string_dtype(ds.dtype) is not None
    if ds.dtype.hasobject and not is_text:
        return None, [], "Variable-length/object payload: schema only; no unpickling."
    if ds.is_virtual or ds.external:
        return None, [], "External/virtual data: schema only."
    row_bytes = math.prod(ds.shape[1:]) * max(ds.dtype.itemsize, 1) if ds.ndim else ds.dtype.itemsize
    if row_bytes > MAX_SAMPLE_BYTES:
        return None, [], "A single row exceeds the sample byte budget."
    if ds.ndim == 0:
        return np.asarray(ds[()]), ["scalar"], None
    target = min(SAMPLE_ROWS, ds.shape[0], max(1, MAX_SAMPLE_BYTES // max(1, row_bytes)))
    # Variable-length strings do not have a known byte size; keep their sample tiny.
    if ds.dtype.hasobject:
        target = min(target, 16)
    if target >= ds.shape[0]:
        return ds[:], [[0, ds.shape[0]]], None
    blocks = min(5, target)
    width = max(1, target // blocks)
    starts = np.linspace(0, ds.shape[0] - width, blocks, dtype=np.int64)
    slices = [[int(start), int(start + width)] for start in starts]
    return np.concatenate([ds[a:b] for a, b in slices], axis=0), slices, None


def string_list(value):
    """Read plain labels or pandas' simple protocol-0 string list, without unpickling."""
    raw = json_value(value)
    if isinstance(raw, list) and all(isinstance(x, str) for x in raw):
        return raw
    if not isinstance(raw, str) or len(raw) > 100000:
        return None
    try:
        ops = list(pickletools.genops(raw.encode("utf-8")))
        names = [op.name for op, _, _ in ops]
        if names[:3] != ["MARK", "LIST", "PUT"] or names[-1:] != ["STOP"]:
            return None
        middle = ops[3:-1]
        if len(middle) % 3:
            return None
        labels = []
        for i in range(0, len(middle), 3):
            if [op.name for op, _, _ in middle[i:i+3]] != ["UNICODE", "PUT", "APPEND"]:
                return None
            labels.append(middle[i][1])
        return labels
    except Exception:
        return None


def find_column_labels(ds):
    """Recover common h5py and pandas-fixed column label conventions."""
    expected = ds.shape[1] if ds.shape is not None and ds.ndim == 2 else None
    if expected is None:
        return None
    candidates = ["columns", "column_names", "feature_names", "variables"]
    for key in candidates:
        if key in ds.attrs:
            raw = string_list(ds.attrs[key])
            if raw is not None and len(raw) == expected:
                return raw
    leaf = ds.name.rsplit("/", 1)[-1]
    if leaf.endswith("_values"):
        candidates.insert(0, leaf[:-7] + "_items")
    candidates.append("axis0")
    for key in candidates:
        # Do not follow soft links or external files while guessing label locations.
        if not isinstance(ds.parent.get(key, getlink=True), h5py.HardLink):
            continue
        obj = ds.parent[key]
        if (isinstance(obj, h5py.Dataset) and obj.shape == (expected,)
                and expected <= 10000 and h5py.check_string_dtype(obj.dtype) is not None):
            return json_value(obj[:])
    return None


def describe_values(values):
    arr = np.asarray(values).ravel()
    result = {"sampled_values": int(arr.size), "dtype": str(arr.dtype)}
    if arr.dtype.kind in "biuf":
        finite_mask = np.isfinite(arr)
        finite = arr[finite_mask]
        result.update({"nonfinite": int((~finite_mask).sum()),
                       "nan": int(np.isnan(arr).sum()),
                       "positive_infinity": int(np.isposinf(arr).sum()),
                       "negative_infinity": int(np.isneginf(arr).sum())})
        if finite.size:
            result.update({"min": json_value(finite.min()), "max": json_value(finite.max()),
                           "mean": json_value(float(np.mean(finite, dtype=np.float64))),
                           "std": json_value(float(np.std(finite, dtype=np.float64))),
                           "negative": int((finite < 0).sum()), "zero": int((finite == 0).sum()),
                           "positive": int((finite > 0).sum())})
            unique, counts = np.unique(finite, return_counts=True)
            if len(unique) <= 20:
                result["sample_value_counts"] = [{"value": json_value(v), "count": int(n)}
                                                 for v, n in zip(unique, counts)]
    elif arr.dtype.kind in "SUO":
        labels = [str(json_value(x)) for x in arr]
        counts = Counter(labels)
        result["unique_in_sample"] = len(counts)
        result["most_common_in_sample"] = counts.most_common(20)
    return result


def describe_sample(sample, labels=None, field_labels=None):
    result = {}
    field_labels = field_labels or {}

    def add_array(name, arr, labels_for_array=None):
        arr = np.asarray(arr)
        if arr.dtype.names:
            for field in arr.dtype.names:
                add_array(f"{name}.{field}" if name else field, arr[field], field_labels.get(field))
            return
        if arr.ndim <= 1:
            result[name or "value"] = describe_values(arr)
            return
        width = math.prod(arr.shape[1:])
        if width > MAX_DIAGNOSTIC_COLUMNS:
            result[name or "all_components"] = describe_values(arr)
            result[name or "all_components"]["note"] = "Components pooled; see shape and labels."
            return
        flat = arr.reshape(arr.shape[0], width)
        for index in range(width):
            key = str(labels_for_array[index]) if labels_for_array else f"{name or 'column'}[{index}]"
            if key in result:
                key = f"{key} [component {index}]"
            result[key] = describe_values(flat[:, index])

    add_array("", sample, labels)
    return result


def inspect_hdf5(path):
    stat = path.stat()
    report = {
        "file": str(path), "size_bytes": stat.st_size,
        "inspected_utc": datetime.now(timezone.utc).isoformat(),
        "versions": {"h5py": h5py.__version__, "numpy": np.__version__, "pandas": pd.__version__},
        "settings": {"sample_rows_per_dataset": SAMPLE_ROWS, "sample_bytes_per_dataset": MAX_SAMPLE_BYTES},
        "notes": [
            "Dataset shapes are exact metadata. Axis 0 is not automatically an event count.",
            "Statistics use at most five small contiguous windows spread across each dataset.",
            "Samples are deterministic diagnostics, not random or guaranteed representative estimates.",
            "Negative/nonfinite counts and categorical counts apply only to the sampled values.",
            "Pandas fixed-format labels are recovered where available; table labels also appear in attributes.",
            "No units, process meanings, weight normalization, or full-file validity are inferred.",
            "Large compressed chunks may require extra I/O despite small requested slices.",
        ],
        "groups": [], "datasets": [], "errors": [],
    }
    if not h5py.is_hdf5(path):
        raise ValueError(f"Not a readable HDF5 file: {path}")
    with h5py.File(path, "r") as handle:
        report["root_attributes"] = read_attributes(handle)

        def visit(name, obj):
            if isinstance(obj, h5py.Group):
                report["groups"].append({"path": obj.name, "attributes": read_attributes(obj)})
                return
            item = {"path": obj.name, "shape": list(obj.shape) if obj.shape is not None else None,
                    "dtype": str(obj.dtype), "field_names": list(obj.dtype.names or []),
                    "logical_bytes": int(obj.size * obj.dtype.itemsize) if obj.size is not None else 0,
                    "stored_bytes": int(obj.id.get_storage_size()), "chunks": json_value(obj.chunks),
                    "compression": obj.compression, "attributes": read_attributes(obj)}
            report["datasets"].append(item)
            try:
                item["column_labels"] = find_column_labels(obj)
                item["field_column_labels"] = {}
                for field in obj.dtype.names or []:
                    key = field + "_kind"
                    if key in obj.attrs:
                        labels = string_list(obj.attrs[key])
                        if labels is not None and len(labels) == math.prod(obj.dtype[field].shape):
                            item["field_column_labels"][field] = labels
                sample, slices, note = read_sample(obj)
                item["sample_slices_start_stop"] = slices
                if note:
                    item["sample_note"] = note
                if sample is not None:
                    item["sample_shape"] = list(sample.shape)
                    preview = sample if sample.ndim == 0 else sample[:PREVIEW_ROWS]
                    item["preview"] = json_value(preview, limit=300)
                    item["sample_statistics"] = describe_sample(sample, item["column_labels"], item["field_column_labels"])
            except Exception as exc:
                item["sample_error"] = str(exc)
                report["errors"].append({"path": obj.name, "error": str(exc)})

        handle.visititems(visit)
    return report


def make_text_report(report):
    lines = ["HDF5 INSPECTION REPORT", f"File: {report['file']}",
             f"Size: {report['size_bytes']:,} bytes", f"Inspected: {report['inspected_utc']}", ""]
    lines += ["INTERPRETATION"] + ["- " + note for note in report["notes"]]
    lines += ["", "ROOT ATTRIBUTES", json.dumps(report["root_attributes"], indent=2, ensure_ascii=False)]
    for group in report["groups"]:
        lines += ["", "GROUP " + group["path"], json.dumps(group["attributes"], indent=2, ensure_ascii=False)]
    for item in report["datasets"]:
        lines += ["", "DATASET " + item["path"], json.dumps(item, indent=2, ensure_ascii=False)]
    lines += ["", "READ ERRORS", json.dumps(report["errors"], indent=2, ensure_ascii=False)]
    return "\n".join(lines) + "\n"

## 3. Read the schema and bounded samples

This may take a little time on the mounted Drive. HDF5 chunk compression can require reading more bytes than the requested slices. This is an inspection, not a complete integrity scan.

In [4]:
report = inspect_hdf5(FILE_PATH)

schema_rows = []
for item in report["datasets"]:
    schema_rows.append({
        "path": item["path"], "shape": item["shape"], "dtype": item["dtype"],
        "stored_MiB": round(item["stored_bytes"] / 1024**2, 3),
        "compression": item["compression"], "sample_shape": item.get("sample_shape"),
        "note": item.get("sample_error", item.get("sample_note", "")),
    })

print(f"Found {len(report['groups'])} groups and {len(report['datasets'])} datasets.")
print("Shapes are exact; the meaning of each axis must be checked from the layout and labels.")
with pd.option_context("display.max_rows", 200, "display.max_colwidth", 100):
    display(pd.DataFrame(schema_rows))
if report["errors"]:
    print("Some samples could not be read; the report includes these errors:")
    display(pd.DataFrame(report["errors"]))

Found 1 groups and 12 datasets.
Shapes are exact; the meaning of each axis must be checked from the layout and labels.

,path,shape,dtype,stored_MiB,compression,sample_shape,note
0,/dataset/axis0,[66],|S16,0.001,None,[66],
1,/dataset/axis1,[9540480],int64,72.788,None,[2000],
2,/dataset/block0_items,[34],|S16,0.001,None,[34],
3,/dataset/block0_values,"[9540480, 34]",float32,1237.397,None,"[2000, 34]",
4,/dataset/block1_items,[21],|S12,0.000,None,[21],
5,/dataset/block1_values,"[9540480, 21]",float64,1528.550,None,"[2000, 21]",
6,/dataset/block2_items,[2],|S10,0.000,None,[2],
7,/dataset/block2_values,"[9540480, 2]",int32,72.788,None,"[2000, 2]",
8,/dataset/block3_items,[7],|S5,0.000,None,[7],
9,/dataset/block3_values,"[9540480, 7]",int64,509.517,None,"[2000, 7]",
10,/dataset/block4_items,[2],|S7,0.000,None,[2],
11,/dataset/block4_values,[1],object,1.000,None,None,Variable-length/object payload: schema only; no unpickling.

## 4. Attributes, column names, and example entries

This output can reveal feature names, process labels, event identifiers, weight definitions, or preprocessing metadata when they are actually stored in the file. Names alone do not establish units or physics conventions.

In [5]:
print("ROOT ATTRIBUTES")
print(json.dumps(report["root_attributes"], indent=2, ensure_ascii=False))
for group in report["groups"]:
    print("\nGROUP", group["path"])
    print(json.dumps(group["attributes"], indent=2, ensure_ascii=False))

for item in report["datasets"]:
    print("\nDATASET", item["path"], "| shape:", item["shape"], "| dtype:", item["dtype"])
    for key in ("field_names", "column_labels", "field_column_labels", "attributes", "sample_slices_start_stop", "preview", "sample_note", "sample_error"):
        if item.get(key) is not None and item.get(key) != [] and item.get(key) != {}:
            print(key + ":", json.dumps(item[key], indent=2, ensure_ascii=False))

ROOT ATTRIBUTES
{
  "CLASS": "GROUP",
  "PYTABLES_FORMAT_VERSION": "2.1",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "1.0"
}

GROUP /dataset
{
  "CLASS": "GROUP",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "1.0",
  "axis0_variety": "regular",
  "axis1_variety": "regular",
  "block0_items_variety": "regular",
  "block1_items_variety": "regular",
  "block2_items_variety": "regular",
  "block3_items_variety": "regular",
  "block4_items_variety": "regular",
  "encoding": "UTF-8",
  "errors": "strict",
  "nblocks": 5,
  "ndim": 2,
  "pandas_type": "frame",
  "pandas_version": "0.15.2"
}

DATASET /dataset/axis0 | shape: [66] | dtype: |S16
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "kind": "string",
  "name": "N.",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    66
  ]
]
preview: [
  "MCFM_dxs_HZZ",
  "MCFM_dxs_ggZZbox",
  "MCFM_dxs_ggZZtot"
]

DATASET /dataset/axis1 | shape: [9540480] | dtype: int64
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "kind": "integer",
  "name": "N.",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    400
  ],
  [
    2385020,
    2385420
  ],
  [
    4770040,
    4770440
  ],
  [
    7155060,
    7155460
  ],
  [
    9540080,
    9540480
  ]
]
preview: [
  0,
  1,
  2
]

DATASET /dataset/block0_items | shape: [34] | dtype: |S16
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "kind": "string",
  "name": "N.",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    34
  ]
]
preview: [
  "MCFM_dxs_HZZ",
  "MCFM_dxs_ggZZbox",
  "MCFM_dxs_ggZZtot"
]

DATASET /dataset/block0_values | shape: [9540480, 34] | dtype: float32
column_labels: [
  "MCFM_dxs_HZZ",
  "MCFM_dxs_ggZZbox",
  "MCFM_dxs_ggZZtot",
  "MCFM_dxs_ZZ",
  "m4l_fsr",
  "cth1_fsr",
  "cth2_fsr",
  "cthstr_fsr",
  "phi1_fsr",
  "phi_fsr",
  "pt4l_fsr",
  "mZ1_fsr",
  "mZ2_fsr",
  "y4l_fsr",
  "eta4l_fsr",
  "dijet_deltaeta",
  "dijet_deltaphi",
  "dijet_invmass",
  "cosPhi",
  "cosPhi1",
  "log_m4l_fsr",
  "log_pt4l_fsr",
  "deltaEta",
  "deltaM",
  "deltaPhi",
  "NN_disc_New",
  "r_SBI",
  "r_B",
  "r_S",
  "r_qqZZ",
  "r_EWB",
  "r_EWSBI",
  "r_EWSBI10",
  "r_ttV"
]
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    400
  ],
  [
    2385020,
    2385420
  ],
  [
    4770040,
    4770440
  ],
  [
    7155060,
    7155460
  ],
  [
    9540080,
    9540480
  ]
]
preview: [
  [
    3.007734339366408e-11,
    3.7059761509583566e-11,
    3.4880841270901186e-11,
    3.947028481832149e-09,
    384.42877197265625,
    0.20038403570652008,
    -0.05083740875124931,
    -0.30930012464523315,
    -0.08139117807149887,
    -1.8222527503967285,
    72.16658782958984,
    88.10990142822266,
    96.5145034790039,
    -0.014997156336903572,
    -0.08119857311248779,
    4.852031230926514,
    4.675563335418701,
    474.79852294921875,
    -0.24881483614444733,
    0.9966895580291748,
    5.95175838470459,
    4.371554374694824,
    4.852031230926514,
    6.162890434265137,
    -0.03681732341647148,
    0.8071225881576538,
    0.12185279279947281,
    0.11974026262760162,
    1.0144037008285522,
    0.03108956292271614,
    0.4203818440437317,
    0.1350381225347519,
    0.9309840202331543,
    0.024120314046740532
  ],
  [
    5.997010613795206e-12,
    3.1460539728911385e-10,
    2.999312742613114e-10,
    3.187977881680126e-08,
    280.49163818359375,
    -0.42292457818984985,
    -0.8354403972625732,
    -0.5606194734573364,
    1.830588459968567,
    -1.7888962030410767,
    43.99159240722656,
    91.91297149658203,
    84.74869537353516,
    1.0314011573791504,
    2.764146089553833,
    -999.0,
    -999.0,
    -999.0,
    -0.21637490391731262,
    -0.25687965750694275,
    5.6365437507629395,
    3.9316606521606445,
    2.437537670135498,
    5.748476982116699,
    -0.37025579810142517,
    -0.48014765977859497,
    8.49372673034668,
    8.174637794494629,
    1.4377505779266357,
    5.09686803817749,
    0.46242424845695496,
    0.7706336379051208,
    0.7372956871986389,
    1.3353689908981323
  ],
  [
    6.876985786385958e-11,
    6.646044131697337e-11,
    4.7167079270105106e-11,
    1.147787753730256e-09,
    461.8741760253906,
    0.18569804728031158,
    0.048386819660663605,
    0.037912946194410324,
    1.6311933994293213,
    3.021845579147339,
    70.37145233154297,
    93.90573120117188,
    85.30193328857422,
    -0.3695240616798401,
    -1.6507641077041626,
    -999.0,
    -999.0,
    -999.0,
    -0.9928388595581055,
    -0.06036036089062691,
    6.1352925300598145,
    4.348618030548096,
    2.437537670135498,
    5.748476982116699,
    -0.37025579810142517,
    0.9622820019721985,
    0.10395707935094833,
    0.14249351620674133,
    1.7453633546829224,
    0.05650506168603897,
    0.23629745841026306,
    0.08719079941511154,
    0.5122595429420471,
    0.01317107118666172
  ]
]

DATASET /dataset/block1_items | shape: [21] | dtype: |S12
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "kind": "string",
  "name": "N.",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    21
  ]
]
preview: [
  "weight",
  "lepPt1",
  "lepPt2"
]

DATASET /dataset/block1_values | shape: [9540480, 21] | dtype: float64
column_labels: [
  "weight",
  "lepPt1",
  "lepPt2",
  "lepPt3",
  "lepPt4",
  "lepEta1",
  "lepEta2",
  "lepEta3",
  "lepEta4",
  "lepPhi1",
  "lepPhi2",
  "lepPhi3",
  "lepPhi4",
  "jetPt1",
  "jetPt2",
  "jetEta1",
  "jetEta2",
  "jetPhi1",
  "jetPhi2",
  "weight_kFact",
  "truth_class"
]
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    400
  ],
  [
    2385020,
    2385420
  ],
  [
    4770040,
    4770440
  ],
  [
    7155060,
    7155460
  ],
  [
    9540080,
    9540480
  ]
]
preview: [
  [
    1.4090569493419025e-05,
    50.28254699707031,
    110.34475708007812,
    105.17975616455078,
    87.30634307861328,
    -1.0404421091079712,
    0.06578615307807922,
    0.38010045886039734,
    0.09378485381603241,
    0.6288343071937561,
    0.4152083992958069,
    2.7315053939819336,
    -2.544292688369751,
    50.511348724365234,
    34.70766830444336,
    -3.899651288986206,
    0.9523800015449524,
    -0.39912304282188416,
    -2.0067451000213623,
    1.8502341642530557e-05,
    1.0
  ],
  [
    1.4272975022322498e-05,
    98.70250701904297,
    42.71342086791992,
    87.5938720703125,
    20.440427780151367,
    0.5919663310050964,
    0.5317221879959106,
    1.5813310146331787,
    1.7654935121536255,
    2.782017469406128,
    -1.9302712678909302,
    0.21649648249149323,
    -3.0754141807556152,
    2.4375377,
    2.4375377,
    -0.00350931566208601,
    0.0037551461718976498,
    -0.001884299679659307,
    -0.010561620816588402,
    1.6077700015021184e-05,
    1.0
  ],
  [
    1.588418126630131e-05,
    111.400634765625,
    155.07186889648438,
    94.26097869873047,
    105.52660369873047,
    -0.2927899956703186,
    -0.33564040064811707,
    -0.4148833155632019,
    -0.45975804328918457,
    1.2185606956481934,
    1.9477894306182861,
    -1.8924951553344727,
    -1.0100326538085938,
    68.17443084716797,
    2.4375377,
    -0.049555543810129166,
    0.0037551461718976498,
    -1.2056084871292114,
    -0.010561620816588402,
    1.9902784782840736e-05,
    1.0
  ]
]

DATASET /dataset/block2_items | shape: [2] | dtype: |S10
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "kind": "string",
  "name": "N.",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    2
  ]
]
preview: [
  "n_jets",
  "event_type"
]

DATASET /dataset/block2_values | shape: [9540480, 2] | dtype: int32
column_labels: [
  "n_jets",
  "event_type"
]
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    400
  ],
  [
    2385020,
    2385420
  ],
  [
    4770040,
    4770440
  ],
  [
    7155060,
    7155460
  ],
  [
    9540080,
    9540480
  ]
]
preview: [
  [
    2,
    1
  ],
  [
    0,
    1
  ],
  [
    1,
    0
  ]
]

DATASET /dataset/block3_items | shape: [7] | dtype: |S5
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "kind": "string",
  "name": "N.",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    7
  ]
]
preview: [
  "lepM1",
  "lepM2",
  "lepM3"
]

DATASET /dataset/block3_values | shape: [9540480, 7] | dtype: int64
column_labels: [
  "lepM1",
  "lepM2",
  "lepM3",
  "lepM4",
  "2jet",
  "1jet",
  "label"
]
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    400
  ],
  [
    2385020,
    2385420
  ],
  [
    4770040,
    4770440
  ],
  [
    7155060,
    7155460
  ],
  [
    9540080,
    9540480
  ]
]
preview: [
  [
    1,
    1,
    1,
    1,
    1,
    1,
    0
  ],
  [
    1,
    1,
    1,
    1,
    0,
    0,
    0
  ],
  [
    2,
    2,
    2,
    2,
    0,
    1,
    0
  ]
]

DATASET /dataset/block4_items | shape: [2] | dtype: |S7
attributes: {
  "CLASS": "ARRAY",
  "FLAVOR": "numpy",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "2.4",
  "kind": "string",
  "name": "N.",
  "transposed": 1
}
sample_slices_start_stop: [
  [
    0,
    2
  ]
]
preview: [
  "Type",
  "subType"
]

DATASET /dataset/block4_values | shape: [1] | dtype: object
attributes: {
  "CLASS": "VLARRAY",
  "PSEUDOATOM": "object",
  "TITLE": {
    "null_attribute": true,
    "dtype": "|S1"
  },
  "VERSION": "1.4",
  "transposed": 1
}
sample_note: "Variable-length/object payload: schema only; no unpickling."

## 5. Sample diagnostics

For numerical columns: finite ranges, mean and standard deviation, NaN/infinity counts, and negative/zero/positive counts. Low-cardinality values and string labels also receive sample frequency counts. A zero negative count does not prove the whole dataset has no negative weights; no luminosity or yield normalization is assumed.

In [6]:
for item in report["datasets"]:
    stats = item.get("sample_statistics", {})
    if not stats:
        continue
    print("\nSAMPLE DIAGNOSTICS:", item["path"])
    rows = [{"variable": name, **values} for name, values in stats.items()]
    with pd.option_context("display.max_rows", 200, "display.max_columns", 16, "display.max_colwidth", 80):
        display(pd.DataFrame(rows))

SAMPLE DIAGNOSTICS: /dataset/axis0

,variable,sampled_values,dtype,unique_in_sample,most_common_in_sample
0,value,66,|S16,66,"[(MCFM_dxs_HZZ, 1), (MCFM_dxs_ggZZbox, 1), (MCFM_dxs_ggZZtot, 1), (MCFM_dxs_..."

SAMPLE DIAGNOSTICS: /dataset/axis1

,variable,sampled_values,dtype,nonfinite,nan,positive_infinity,negative_infinity,min,max,mean,std,negative,zero,positive
0,value,2000,int64,0,0,0,0,0,9540479,4770239.5,3.372928e+06,0,1,1999

SAMPLE DIAGNOSTICS: /dataset/block0_items

,variable,sampled_values,dtype,unique_in_sample,most_common_in_sample
0,value,34,|S16,34,"[(MCFM_dxs_HZZ, 1), (MCFM_dxs_ggZZbox, 1), (MCFM_dxs_ggZZtot, 1), (MCFM_dxs_..."

SAMPLE DIAGNOSTICS: /dataset/block0_values

,variable,sampled_values,dtype,nonfinite,nan,positive_infinity,negative_infinity,min,max,mean,std,negative,zero,positive
0,MCFM_dxs_HZZ,2000,float32,0,0,0,0,2.104343e-15,3.613322e-08,5.142423e-10,2.009679e-09,0,0,2000
1,MCFM_dxs_ggZZbox,2000,float32,0,0,0,0,4.048714e-14,6.062354e-08,1.578740e-09,3.530835e-09,0,0,2000
2,MCFM_dxs_ggZZtot,2000,float32,0,0,0,0,4.361577e-14,5.910285e-08,1.260696e-09,2.901721e-09,0,0,2000
3,MCFM_dxs_ZZ,2000,float32,0,0,0,0,5.718590e-12,2.280999e-05,1.992932e-07,8.133795e-07,0,0,2000
4,m4l_fsr,2000,float32,0,0,0,0,1.806933e+02,1.998364e+03,3.946050e+02,2.501430e+02,0,0,2000
5,cth1_fsr,2000,float32,0,0,0,0,-9.932702e-01,9.998385e-01,1.921719e-02,5.100642e-01,995,0,1005
6,cth2_fsr,2000,float32,0,0,0,0,-9.979592e-01,9.971020e-01,-1.988254e-03,5.287371e-01,997,0,1003
7,cthstr_fsr,2000,float32,0,0,0,0,-9.994916e-01,9.991201e-01,4.333854e-03,5.682751e-01,995,0,1005
8,phi1_fsr,2000,float32,0,0,0,0,-3.136217e+00,3.135348e+00,-1.457370e-02,1.801598e+00,1006,0,994
9,phi_fsr,2000,float32,0,0,0,0,-3.126254e+00,3.133769e+00,-2.426295e-02,1.800420e+00,1038,0,962
10,pt4l_fsr,2000,float32,0,0,0,0,1.793030e+00,7.760214e+02,7.935800e+01,8.114741e+01,0,0,2000
11,mZ1_fsr,2000,float32,0,0,0,0,7.117924e+01,1.046093e+02,9.088288e+01,2.513739e+00,0,0,2000
12,mZ2_fsr,2000,float32,0,0,0,0,6.048149e+01,1.148911e+02,8.881273e+01,8.227169e+00,0,0,2000
13,y4l_fsr,2000,float32,0,0,0,0,-2.291858e+00,2.160663e+00,7.417308e-04,8.506123e-01,1000,0,1000
14,eta4l_fsr,2000,float32,0,0,0,0,-6.355538e+00,6.151918e+00,-4.933289e-03,2.444045e+00,1000,0,1000
15,dijet_deltaeta,2000,float32,0,0,0,0,-9.990000e+02,7.463469e+00,-6.854803e+02,4.644856e+02,1374,0,626
16,dijet_deltaphi,2000,float32,0,0,0,0,-9.990000e+02,6.276805e+00,-6.853203e+02,4.647225e+02,1374,0,626
17,dijet_invmass,2000,float32,0,0,0,0,-9.990000e+02,2.401969e+03,-5.429372e+02,7.325942e+02,1374,0,626
18,cosPhi,2000,float32,0,0,0,0,-9.999694e-01,9.999929e-01,1.239704e-02,7.100303e-01,977,0,1023
19,cosPhi1,2000,float32,0,0,0,0,-9.999856e-01,9.999999e-01,-9.285238e-03,6.846353e-01,1009,0,991
20,log_m4l_fsr,2000,float32,0,0,0,0,5.196801e+00,7.600084e+00,5.843860e+00,4.792445e-01,0,0,2000
21,log_pt4l_fsr,2000,float32,0,0,0,0,2.173959e+00,6.663160e+00,4.136493e+00,7.864147e-01,0,0,2000
22,deltaEta,2000,float32,0,0,0,0,1.871586e-03,7.463469e+00,2.507312e+00,1.112086e+00,0,0,2000
23,deltaM,2000,float32,0,0,0,0,3.130359e+00,7.784044e+00,5.689362e+00,6.177530e-01,0,0,2000
24,deltaPhi,2000,float32,0,0,0,0,-9.999751e-01,9.999797e-01,-2.480928e-01,4.400982e-01,1684,0,316
25,NN_disc_New,2000,float32,0,0,0,0,-8.498889e-01,1.089613e+00,-1.065030e-01,5.611618e-01,1236,0,764
26,r_SBI,2000,float32,0,0,0,0,4.232396e-05,4.190382e+01,4.074892e+00,6.056785e+00,0,0,2000
27,r_B,2000,float32,0,0,0,0,1.593155e-04,3.986413e+01,4.019740e+00,5.962728e+00,0,0,2000
28,r_S,2000,float32,0,0,0,0,1.396084e-03,2.401208e+00,1.163728e+00,6.910856e-01,0,0,2000
29,r_qqZZ,2000,float32,0,0,0,0,2.554496e-05,3.901257e+01,3.763452e+00,5.408161e+00,0,0,2000
30,r_EWB,2000,float32,0,0,0,0,2.559992e-02,3.956106e+00,9.140884e-01,7.250538e-01,0,0,2000
31,r_EWSBI,2000,float32,0,0,0,0,4.783652e-03,4.036951e+00,1.062656e+00,8.506626e-01,0,0,2000
32,r_EWSBI10,2000,float32,0,0,0,0,5.815355e-02,1.675896e+00,8.910380e-01,4.631155e-01,0,0,2000
33,r_ttV,2000,float32,0,0,0,0,6.638174e-06,1.396492e+02,1.735743e+00,6.895566e+00,0,0,2000

SAMPLE DIAGNOSTICS: /dataset/block1_items

,variable,sampled_values,dtype,unique_in_sample,most_common_in_sample
0,value,21,|S12,21,"[(weight, 1), (lepPt1, 1), (lepPt2, 1), (lepPt3, 1), (lepPt4, 1), (lepEta1, ..."

SAMPLE DIAGNOSTICS: /dataset/block1_values

,variable,sampled_values,dtype,nonfinite,nan,positive_infinity,negative_infinity,min,max,mean,std,negative,zero,positive,sample_value_counts
0,weight,2000,float64,0,0,0,0,-0.007503,0.007718,0.000210,0.000815,86,0,1914,NaN
1,lepPt1,2000,float64,0,0,0,0,5.974718,902.609009,82.250117,72.145788,0,0,2000,NaN
2,lepPt2,2000,float64,0,0,0,0,5.301942,733.460510,84.811527,73.895223,0,0,2000,NaN
3,lepPt3,2000,float64,0,0,0,0,5.221328,589.645203,82.583878,72.754544,0,0,2000,NaN
4,lepPt4,2000,float64,0,0,0,0,5.259071,682.268982,82.471544,76.223026,0,0,2000,NaN
5,lepEta1,2000,float64,0,0,0,0,-2.664276,2.644820,-0.001460,1.117236,1025,0,975,NaN
6,lepEta2,2000,float64,0,0,0,0,-2.673811,2.674754,0.007814,1.138756,982,0,1018,NaN
7,lepEta3,2000,float64,0,0,0,0,-2.694445,2.649986,-0.006595,1.148471,997,0,1003,NaN
8,lepEta4,2000,float64,0,0,0,0,-2.675636,2.679353,0.007757,1.156181,1015,0,985,NaN
9,lepPhi1,2000,float64,0,0,0,0,-3.140448,3.138362,-0.051849,1.820939,1028,0,972,NaN
10,lepPhi2,2000,float64,0,0,0,0,-3.139374,3.136627,-0.013271,1.817695,994,0,1006,NaN
11,lepPhi3,2000,float64,0,0,0,0,-3.137666,3.140283,-0.001024,1.799127,1001,0,999,NaN
12,lepPhi4,2000,float64,0,0,0,0,-3.141325,3.136908,0.005034,1.805830,989,0,1011,NaN
13,jetPt1,2000,float64,0,0,0,0,2.437538,687.422607,61.087052,71.654617,0,0,2000,NaN
14,jetPt2,2000,float64,0,0,0,0,2.437538,364.915985,20.028497,32.649124,0,0,2000,NaN
15,jetEta1,2000,float64,0,0,0,0,-4.422767,4.497831,-0.040645,1.631923,1350,0,650,NaN
16,jetEta2,2000,float64,0,0,0,0,-4.461409,4.452682,-0.003504,1.233383,315,0,1685,NaN
17,jetPhi1,2000,float64,0,0,0,0,-3.140959,3.129359,-0.018836,1.485342,1359,0,641,NaN
18,jetPhi2,2000,float64,0,0,0,0,-3.140605,3.123535,-0.017434,1.012156,1686,0,314,NaN
19,weight_kFact,2000,float64,0,0,0,0,-0.007503,0.007718,0.000247,0.000817,86,0,1914,NaN
20,truth_class,2000,float64,0,0,0,0,1.000000,1.000000,1.000000,0.000000,0,0,2000,"[{'value': 1.0, 'count': 2000}]"

SAMPLE DIAGNOSTICS: /dataset/block2_items

,variable,sampled_values,dtype,unique_in_sample,most_common_in_sample
0,value,2,|S10,2,"[(n_jets, 1), (event_type, 1)]"

SAMPLE DIAGNOSTICS: /dataset/block2_values

,variable,sampled_values,dtype,nonfinite,nan,positive_infinity,negative_infinity,min,max,mean,std,negative,zero,positive,sample_value_counts
0,n_jets,2000,int32,0,0,0,0,0,8,1.1405,1.136556,0,678,1322,"[{'value': 0, 'count': 678}, {'value': 1, 'count': 696}, {'value': 2, 'count..."
1,event_type,2000,int32,0,0,0,0,0,3,1.4845,1.166945,0,587,1413,"[{'value': 0, 'count': 587}, {'value': 1, 'count': 382}, {'value': 2, 'count..."

SAMPLE DIAGNOSTICS: /dataset/block3_items

,variable,sampled_values,dtype,unique_in_sample,most_common_in_sample
0,value,7,|S5,7,"[(lepM1, 1), (lepM2, 1), (lepM3, 1), (lepM4, 1), (2jet, 1), (1jet, 1), (labe..."

SAMPLE DIAGNOSTICS: /dataset/block3_values

,variable,sampled_values,dtype,nonfinite,nan,positive_infinity,negative_infinity,min,max,mean,std,negative,zero,positive,sample_value_counts
0,lepM1,2000,int64,0,0,0,0,1,2,1.5465,0.497833,0,0,2000,"[{'value': 1, 'count': 907}, {'value': 2, 'count': 1093}]"
1,lepM2,2000,int64,0,0,0,0,1,2,1.5465,0.497833,0,0,2000,"[{'value': 1, 'count': 907}, {'value': 2, 'count': 1093}]"
2,lepM3,2000,int64,0,0,0,0,1,2,1.5560,0.496854,0,0,2000,"[{'value': 1, 'count': 888}, {'value': 2, 'count': 1112}]"
3,lepM4,2000,int64,0,0,0,0,1,2,1.5560,0.496854,0,0,2000,"[{'value': 1, 'count': 888}, {'value': 2, 'count': 1112}]"
4,2jet,2000,int64,0,0,0,0,0,1,0.3130,0.463714,0,1374,626,"[{'value': 0, 'count': 1374}, {'value': 1, 'count': 626}]"
5,1jet,2000,int64,0,0,0,0,0,1,0.6610,0.473370,0,678,1322,"[{'value': 0, 'count': 678}, {'value': 1, 'count': 1322}]"
6,label,2000,int64,0,0,0,0,0,9,5.0000,4.098780,0,800,1200,"[{'value': 0, 'count': 800}, {'value': 8, 'count': 800}, {'value': 9, 'count..."

SAMPLE DIAGNOSTICS: /dataset/block4_items

  variable  sampled_values dtype  unique_in_sample      most_common_in_sample
0    value               2   |S7                 2  [(Type, 1), (subType, 1)]

## 6. Save the reports to Drive

These small report files can be read independently of the 3.6 GB ntuple. Re-running replaces only the generated reports, never the HDF5 input. The full schema and all collected diagnostics remain in the reports even if notebook tables are visually truncated.

In [7]:
text_path = FILE_PATH.with_name(FILE_PATH.stem + ".inspection.txt")
json_path = FILE_PATH.with_name(FILE_PATH.stem + ".inspection.json")

text_path.write_text(make_text_report(report), encoding="utf-8")
json_path.write_text(json.dumps(report, indent=2, ensure_ascii=False, allow_nan=False) + "\n", encoding="utf-8")

for output in (text_path, json_path):
    print(f"Saved: {output} ({output.stat().st_size:,} bytes)")
print("\nDone. Tell me the inspection reports are ready in Drive.")

Saved: /content/drive/MyDrive/Colab Notebooks/HZZ_OffShell/dataset_wDR_mean_origIndex.inspection.txt (46,803 bytes)
Saved: /content/drive/MyDrive/Colab Notebooks/HZZ_OffShell/dataset_wDR_mean_origIndex.inspection.json (56,003 bytes)

Done. Tell me the inspection reports are ready in Drive.